# Generated by Django 4.2 on 2024-01-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "x_position",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "y_position",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
    ]
