# Generated by Django 4.2 on 2024-01-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="facebook_listing",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="item",
            name="kijiji_listing",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
