# Generated by Django 4.2 on 2024-01-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("land_piece", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "x_position",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "y_position",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "land_piece",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="land_piece.landpiece",
                    ),
                ),
            ],
        ),
    ]
